language: java
jdk: openjdk11
sudo: required
services:
    - docker
script:
    - mvn clean install -B
after_success:
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
    - export IMAGE_NAME=kewynakshlley/geekspace-api
    - docker build -t $IMAGE_NAME
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
