language: java
jdk: openjdk11
sudo: required
services:
    - docker
before_deploy:
    - mvn clean install -B
deploy:
    provider: script
    script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - export IMAGE_NAME=kewynakshlley/geekspace-api
        - docker build -t $IMAGE_NAME .
        - docker push $IMAGE_NAME
    on:
        branch: master
