version: '3.1'
services:
    mysql-server:
        container_name: mysql-server
        image: 'mysql:5.7'
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1214
            MYSQL_DATABASE: "geek"
            MYSQL_USER: "geek"
            MYSQL_PASSWORD: 1214
        ports:
            - 3306:3306
    gsys-api:
        container_name: geekspace-api
        image: 'kewynakshlley/geekspace-api'
        volumes:
            - .:/app
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - mysql-server
